CREATE TABLE MEMBER1(
	MEMBER_ID VARCHAR2(15),
	MEMBER_PW VARCHAR2(13),
	MEMBER_NAME VARCHAR2(15),
	MEMBER_AGE NUMBER,
	MEMBER_GENDER VARCHAR2(5),
	MEMBER_EMAIL VARCHAR2(30),
	PRIMARY KEY(MEMBER_ID)
);